# Generated by Django 6.0.2 on 2026-03-19 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0002_user_is_verified_user_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='backend_cal_chat_id_71703e_idx',
        ),
        migrations.RemoveIndex(
            model_name='callquality',
            name='backend_cal_call_id_478257_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='backend_mes_chat_id_b4115c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='backend_mes_sender__c3b237_idx',
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='is_speaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callquality',
            name='audio_bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callquality',
            name='audio_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callquality',
            name='video_bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='websocket_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='websocket_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callparticipant',
            name='role',
            field=models.CharField(choices=[('initiator', 'Initiator'), ('caller', 'Caller'), ('callee', 'Callee'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['chat', '-started_at'], name='backend_cal_chat_id_a1e88c_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['call', 'is_speaking'], name='backend_cal_call_id_bfd558_idx'),
        ),
        migrations.AddIndex(
            model_name='callquality',
            index=models.Index(fields=['call', '-measured_at'], name='backend_cal_call_id_35d9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='backend_mes_chat_id_c24efd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='backend_mes_sender__cfc8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_message_id'], name='backend_mes_client__e474e3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['websocket_token'], name='backend_use_websock_4ce06d_idx'),
        ),
    ]
